### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by changebio** [GBA-BI/pybioos#2]
bw -h

Traceback (most recent call last):
  File "/home/huang_yin/anaconda3/envs/bios/bin/bw", line 5, in <module>
    from bioos.bioos_workflow import bioos_workflow
  File "/home/huang_yin/anaconda3/envs/bios/lib/python3.11/site-packages/bioos/bioos_workflow.py", line 9, in <module>
    from bioos import bioos
  File "/home/huang_yin/anaconda3/envs/bios/lib/python3.11/site-packages/bioos/bioos.py", line 4, in <module>
    from bioos.config import Config
  File "/home/huang_yin/anaconda3/envs/bios/lib/python3.11/site-packages/bioos/config.py", line 7, in <module>
    from bioos.log import PyLogger
  File "/home/huang_yin/anaconda3/envs/bios/lib/python3.11/site-packages/bioos/log.py", line 4, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by worsteggs** [comment]
pip install colorama will fix it.

**Comment by JaylanLiu** [comment]
Thank for reporting, add colorama install_requires in setup.py in v 0.0.9
